### ISSUE TITLE
Correct errors in Parse and divide to multi part Classes 

### ISSUE THREAD

**Issue by ZeinaDaghlas** [sallyishak/SoftwareConstructionProject#2]
Many errors in the code logic need to be correct by Sun . 
[project_1.pdf](https://github.com/sallyishak/SoftwareConstructionProject/files/679121/project_1.pdf)

**Comment by sallyishak** [comment]
This issue is resolved now after meeting with team member and discussed the errors on Skype. 
Remal and Zeina, please check the classes you were assigned to and confirm you don't have any issues.

**Comment by ZeinaDaghlas** [comment]
Hi Sally , 

thank you everything seems fine ,, waiting Remal feedback to close the issue. 
No bugs nothing wrong in the code. thank you :) 

Zeina

**Comment by remalsaad** [comment]
Hi all,
Confirmed ,There are no bugs with the errors.
Remal

**Comment by ZeinaDaghlas** [comment]
thank you , 

we will close this issue, since it was solved .
